/*
 * Desafio conductor
 *
 * Api para controle de trasacoes de contas
 *
 * API version: 1.0.0
 * Contact: thiagorodriguescamara@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Transaction struct {
	Id string `json:"id" pdf:"false"`

	AccountId string `json:"id_conta" pdf:"true" size:"100" header:"Conta"`

	Description string `json:"descricao" pdf:"true" size:"50" header:"Transacao"`

	Value float64 `json:"valor" pdf:"true" size:"50" header:"Valor"`
}
