/*
 * Desafio conductor
 *
 * Api para controle de trasacoes de contas
 *
 * API version: 1.0.0
 * Contact: thiagorodriguescamara@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Transaction struct {

	Id string `json:"id,omitempty"`

	AccountId string `json:"accountId,omitempty"`

	Description string `json:"description,omitempty"`

	Value float32 `json:"value,omitempty"`
}
