/*
 * Desafio conductor
 *
 * Api para controle de trasacoes de contas
 *
 * API version: 1.0.0
 * Contact: thiagorodriguescamara@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package controllers

import (
	"encoding/json"
	"net/http"
)

//Accounts returne all accounts
func (c *Controller) Accounts(w http.ResponseWriter, r *http.Request) {

	accounts, err := c.Db.FindAllAccounts()

	if err != nil {
		json.NewEncoder(w).Encode(map[string]string{"Error": err.Error()})
	}

	json.NewEncoder(w).Encode(accounts)
}
