/*
 * Desafio conductor
 *
 * Api para controle de trasacoes de contas
 *
 * API version: 1.0.0
 * Contact: thiagorodriguescamara@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package controllers

import (
	"io/ioutil"
	"net/http"

	"github.com/ThiagoRodriguesdeSantana/desafio_conductor/go-server-server/go/file"
	"github.com/gorilla/mux"
)

func (c *Controller) TransactionsPDF(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)

	id := vars["id"]

	acc, _ := c.Db.FindTransactionByAccountID(id)

	file := file.NewPDF()

	path := file.GeneratePDF(acc)

	filePdf, _ := ioutil.ReadFile(path)

	w.Write(filePdf)
}
