/*
 * Desafio conductor
 *
 * Api para controle de trasacoes de contas
 *
 * API version: 1.0.0
 * Contact: thiagorodriguescamara@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/ThiagoRodriguesdeSantana/desafio_conductor/go-server-server/go/go-server-server/go/controllers"
	"github.com/ThiagoRodriguesdeSantana/desafio_conductor/go-server-server/go/go-server-server/go/repository"
	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

var controller *controllers.Controller

func NewRouter() *mux.Router {

	db := repository.InitDB()

	controller = controllers.NewController(db)

	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"Account",
		strings.ToUpper("Get"),
		"/v1/contas/{id}",
		controller.Account,
	},

	Route{
		"Accounts",
		strings.ToUpper("Get"),
		"/v1/contas",
		controller.Accounts,
	},

	Route{
		"Transactions",
		strings.ToUpper("Get"),
		"/v1/contas/{id}/transacoes",
		controller.Transactions,
	},
}
