---
swagger: "2.0"
info:
  description: "Api para controle de trasacoes de contas"
  version: "1.0.0"
  title: "Desafio conductor"
  contact:
    email: "thiagorodriguescamara@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "conductor"
basePath: "/v1"
tags:
- name: "contas"
  description: "Relatorios de contas e transacoes"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Informacoes de contas cadastradas"
schemes:
- "https"
- "http"
paths:
  /contas:
    get:
      tags:
      - "Contas"
      summary: "Busca todas as contas cadastradas"
      description: "Retorna todas as contas existentes no banco"
      operationId: "Accounts"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Account"
        "400":
          description: "Nenhuma conta cadastrada"
  /contas/{id}:
    get:
      tags:
      - "Conta"
      summary: "Busca conta pelo ID"
      description: "Retorna uma unica conta"
      operationId: "Account"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID da conta para retorno"
        required: true
        type: "string"
        x-exportParamName: "Id"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: "Conta nao encontrada"
  /contas/{id}/transacoes:
    get:
      tags:
      - "Transacoes"
      summary: "Busca transacoes da conta"
      description: "Retorna lista de trasacoes da conta"
      operationId: "Transactions"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID da conta para retorno"
        required: true
        type: "string"
        x-exportParamName: "Id"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: "Nao ha trasacoes para essa conta"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Account:
    type: "object"
    properties:
      id:
        type: "string"
      status:
        type: "string"
    xml:
      name: "Account"
    example:
      id: "id"
      status: "status"
  Transaction:
    type: "object"
    properties:
      id:
        type: "string"
      accountId:
        type: "string"
      description:
        type: "string"
      value:
        type: "number"
    xml:
      name: "Transaction"
    example:
      accountId: "accountId"
      description: "description"
      id: "id"
      value: 0.80082819046101150206595775671303272247314453125
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
